version: "3.8"

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: drf_db
      POSTGRES_USER: drf_user
      POSTGRES_PASSWORD: drf_pass
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: scripts/wait-for.sh db:5432 python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=drf_db
      - POSTGRES_USER=drf_user
      - POSTGRES_PASSWORD=drf_pass
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

  nginx:
    image: nginx:alpine
    volumes:
      - .:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
